Recipe.create!([
  {title: "Fava Bean side dish", chef: "Hannibal", ingredients: "ice, tap water, 2 lbs fresh fava beans in the pod, 1 tablespoon butter, 1 teaspoon olive oil, 2 garlic cloves", directions: "boil 4 cups of water, add salt, place fava beans in the boiling water for 5 min, remove fava beans and place in ice water, add seasoning to taste", image_url: "http://bijouxs.com/wp-content/uploads/2011/05/Favabordercropsmall.jpg", prep_time: 125},
  {title: "Cookies", chef: "Cookie Monster", ingredients: "cookie mix, milk, eggs", directions: "pour mix into bowl, add milk and eggs, stir well, bake", image_url: "http://1.bp.blogspot.com/-w-i7-dRn_V0/TeZP9aAxPBI/AAAAAAAAAR4/8E_-JCJlEmQ/s1600/Apri2011+055pwm.jpg", prep_time: 480},
  {title: "Hand Sandwich", chef: "Bad Josh", ingredients: "left hand, right hand", directions: "put your hands together, Wisconsin!", image_url: "http://blog.bekahbrunstetter.com/wp-content/uploads/2013/03/hand-sandwich.jpg", prep_time: 1},
  {title: "Lasagna", chef: "Garfield", ingredients: "noodles, tomato paste, meat, onions, garlic, other stuff", directions: "layer noodles, add sauce, layer noodles, add meat, layer noodles, add onions, layer noodles, add other stuff, finish with a layer of noodles", image_url: "https://media1.tenor.com/images/93ecc4025061be714f5c1861eb3c2406/tenor.gif?itemid=3571569", prep_time: 60},
  {title: "Raw Egg", chef: "Josh", ingredients: "chicken, egg", directions: "squeeze chicken", image_url: "https://boost-rankedboost.netdna-ssl.com/wp-content/uploads/2016/07/Pokemon-Go-Egg.png", prep_time: 4},
  {title: "Ratatouille", chef: "Remy", ingredients: " 1 Large Zucchini, 1 Large Yellow Summer Squash, 2 Small Eggplants, 1 Red Bell Pepper, 1/2 Small Yellow Onion, 2 Garlic Cloves, 15 oz. can Crushed Tomatoes, Fresh Thyme, 1 tsp Salt", directions: "mix them", image_url: "https://www.foodlion.com/content/dam/food-lion/recipes/Ratatouille1/ratatouille_MAIN_IMAGE.jpg.adapt.full.high.jpg", prep_time: 43}
])

